// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: unfollow.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const feedUnfollow = `-- name: FeedUnfollow :exec
DELETE FROM feed_follows
WHERE user_id = $1 AND feed_id = $2
`

type FeedUnfollowParams struct {
	UserID uuid.UUID
	FeedID uuid.UUID
}

func (q *Queries) FeedUnfollow(ctx context.Context, arg FeedUnfollowParams) error {
	_, err := q.db.ExecContext(ctx, feedUnfollow, arg.UserID, arg.FeedID)
	return err
}
